### ISSUE TITLE
QnibSetup does not find etcd

### ISSUE THREAD

**Issue by goerge** [ChristianKniep/docker-elk#5]
Hi,
after setting up docker-elk as advised, `supervisord.log` states
```
2015-01-28 16:57:48,282 INFO exited: statsd (exit status 1; not expected)
2015-01-28 16:57:48,300 INFO exited: setup (exit status 1; not expected)
```

`setup.log`  details
```
Traceback (most recent call last):
  File "/usr/local/bin/qnib-setup.py", line 21, in <module>
    from qnibsetup import QnibConfig, QnibSetup
  File "/usr/lib/python2.7/site-packages/qnibsetup/__init__.py", line 9, in <module>
    from qnibsetup.setup import QnibSetup
  File "/usr/lib/python2.7/site-packages/qnibsetup/setup.py", line 12, in <module>
    import etcd
ImportError: No module named etcd
```

Any idea how to solve this?
Thanks in advance!

**Comment by ChristianKniep** [comment]
Hey #goerge,

I am currently refining it by switching to consul. Consul is etcd,dns and a lightweight nagios... It's going to be awesome.
In the meantime you should just ignore the logs. qnib/elk is working fine. The integration within QNIBTerminal has to be fixed due to the new approach. I am currently using it in combination with influxdb and grafana. 
http://qnib.org/2015/01/15/Grafana-analytic-stack/

Cheers

**Comment by ChristianKniep** [comment]
I guess the issue is outdated.
